# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - InstantCoderBackend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: # Environment variables defined at the job level
      ADMIN_EMAIL: ${{ vars.ADMIN_EMAIL }}
      ADMIN_PASSWORD: ${{ vars.ADMIN_PASSWORD }}
      CLOUDINARY_API_KEY: ${{ vars.CLOUDINARY_API_KEY }}
      CLOUDINARY_NAME: ${{ vars.CLOUDINARY_NAME }}
      CLOUDINARY_SECRET_KEY: ${{ vars.CLOUDINARY_SECRET_KEY }}
      CURRENCY: ${{ vars.CURRENCY }}
      EMAIL_SERVICE_PASSWORD: ${{ vars.EMAIL_SERVICE_PASSWORD }}
      EMAIL_SERVICE_SMTP: ${{ vars.EMAIL_SERVICE_SMTP }}
      JWT_SECRET: ${{ vars.JWT_SECRET }}
      MONGODB_URI: ${{ vars.MONGODB_URI }}
      PORT: ${{ vars.PORT }}
      VITE_BACKEND_URL: ${{ vars.VITE_BACKEND_URL }}
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Print environment variables
        run: printenv
      
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D200E5631D104C27BA28D97ED7FC702F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_70168E1EE40C421AAA14DD5158B1D7EE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2695889E72FE4DD29E6270446674BDB8 }}
        
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'InstantCoderBackend'
          slot-name: 'Production'
          package: .
          
